BOX_IMAGE = "jeffnoxon/ubuntu-20.04-arm64"
BOX_VERSION = "1.0.0"

N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.define "hk8s-m" do |master|
        master.vm.box = BOX_IMAGE
        master.vm.box_version = BOX_VERSION
        master.vm.network "private_network", ip: "192.168.56.50"
        master.vm.hostname = "hk8s-m"
        master.vm.provider "parallels" do |v|
          v.cpus = 2
          v.memory = 2048
          v.linked_clone = true
        end
        master.vm.provision "ansible" do |ansible|
          ansible.playbook = "roles/hk8s.yml"
            ansible.extra_vars = {
                ansible_python_interpreter: "/usr/bin/python3",
                node_ip: "192.168.56.50",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "hk8s-w#{i}" do |worker|
            worker.vm.box = BOX_IMAGE
            worker.vm.box_version = BOX_VERSION
            worker.vm.network "private_network", ip: "192.168.56.#{i + 10}"
            worker.vm.hostname = "hk8s-w#{i}"
            worker.vm.provider "parallels" do |v|
              v.cpus = 2
              v.memory = 2048
              v.linked_clone = true
            end
            worker.vm.provision "ansible" do |ansible|
                ansible.playbook = "roles/hk8s.yml"
                ansible.extra_vars = {
                    ansible_python_interpreter: "/usr/bin/python3",
                    node_ip: "192.168.56.#{i + 10}",
                }
            end
        end
    end
end
