action_id: trunk-share-with-everyone
date: 2025-01-14 11:15:04
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1736853304
full_timestamp:
  nanos: 538962000
  seconds: 1736853304
trunk_version: 1.22.8
